'use client'

import { use } from 'react'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Download, FileText, Target, TrendingUp, Shield, BarChart3 } from 'lucide-react'

// Framework data for each framework type
const frameworkData: Record<string, {
  title: string
  subtitle: string
  description: string
  purpose: string
  icon: string
  color: string
  components: {
    title: string
    description: string
    metrics?: string[]
  }[]
  howToUse: {
    step: number
    title: string
    description: string
  }[]
  relatedResources: {
    title: string
    type: string
    available: boolean
  }[]
}> = {
  cimm: {
    title: 'Cultural Innovation Measurement Matrix',
    subtitle: 'CIMM Framework',
    description: 'A four-axis framework for measuring the depth, integrity, impact, and velocity of cultural innovations. The CIMM provides organizations with a comprehensive lens for evaluating how well their innovations balance commercial success with cultural preservation.',
    purpose: 'The CIMM Framework helps organizations systematically assess cultural innovations across multiple dimensions, ensuring that economic growth does not come at the expense of cultural authenticity.',
    icon: 'CM',
    color: 'from-ocean to-sage',
    components: [
      {
        title: 'Innovation Depth Spectrum',
        description: 'Measures the extent to which innovations build upon, extend, or transform traditional cultural practices.',
        metrics: ['Surface-level adaptation', 'Functional enhancement', 'Structural transformation', 'Paradigm innovation']
      },
      {
        title: 'Cultural Integrity Index',
        description: 'Evaluates how well innovations maintain the essential meanings, values, and practices of the source culture.',
        metrics: ['Authenticity preservation (0-100%)', 'Practitioner involvement level', 'Community approval rating', 'Cultural protocol adherence']
      },
      {
        title: 'Economic Impact Metrics',
        description: 'Quantifies the financial returns and economic benefits generated by cultural innovations.',
        metrics: ['Direct revenue generation', 'Employment creation', 'Supply chain development', 'Export value contribution']
      },
      {
        title: 'Innovation Velocity Tracking',
        description: 'Monitors the speed and consistency of innovation output over time.',
        metrics: ['Time to market', 'Innovation frequency', 'Iteration cycles', 'Market responsiveness']
      }
    ],
    howToUse: [
      { step: 1, title: 'Baseline Assessment', description: 'Score your current initiatives across all four axes using the provided rubrics.' },
      { step: 2, title: 'Gap Analysis', description: 'Identify dimensions where scores fall below optimal thresholds (70%).' },
      { step: 3, title: 'Strategy Development', description: 'Develop targeted interventions for underperforming dimensions.' },
      { step: 4, title: 'Quarterly Review', description: 'Re-assess scores quarterly to track progress and adjust strategies.' }
    ],
    relatedResources: [
      { title: 'CIMM Assessment Workbook', type: 'Excel Template', available: false },
      { title: 'Scoring Rubric Guide', type: 'PDF Guide', available: false },
      { title: 'Case Study Examples', type: 'PDF Document', available: true }
    ]
  },
  cira: {
    title: 'Cultural Innovation Readiness Assessment',
    subtitle: 'CIRA Framework',
    description: "A comprehensive evaluation tool designed to assess a community's or organization's preparedness for undertaking cultural innovation initiatives. CIRA identifies strengths to leverage and gaps to address before launching new ventures.",
    purpose: 'Before investing resources in cultural innovation projects, organizations need to understand their current capabilities and readiness. CIRA provides this crucial diagnostic function.',
    icon: 'RA',
    color: 'from-gold to-terracotta',
    components: [
      {
        title: 'Cultural Capital Inventory',
        description: 'Catalogues the tangible and intangible cultural assets available for innovation.',
        metrics: ['Traditional knowledge documentation', 'Skilled practitioner availability', 'Cultural artifact accessibility', 'Heritage site conditions']
      },
      {
        title: 'Innovation Ecosystem Components',
        description: 'Assesses the supporting infrastructure and networks required for successful innovation.',
        metrics: ['Educational institutions', 'Funding mechanisms', 'Market access channels', 'Technology infrastructure']
      },
      {
        title: 'Barriers Assessment Index',
        description: 'Identifies and quantifies obstacles that may impede cultural innovation success.',
        metrics: ['Regulatory barriers', 'Social resistance levels', 'Resource constraints', 'Market access limitations']
      },
      {
        title: 'Readiness Score Calculation',
        description: 'Aggregates component scores into an overall readiness percentage.',
        metrics: ['Component weighted average', 'Threshold comparison', 'Peer benchmarking', 'Trend analysis']
      }
    ],
    howToUse: [
      { step: 1, title: 'Stakeholder Mapping', description: 'Identify all stakeholders who should participate in the assessment process.' },
      { step: 2, title: 'Data Collection', description: 'Gather quantitative and qualitative data for each component area.' },
      { step: 3, title: 'Scoring Workshop', description: 'Conduct collaborative scoring sessions with diverse stakeholder groups.' },
      { step: 4, title: 'Action Planning', description: 'Develop readiness improvement plans targeting low-scoring areas.' }
    ],
    relatedResources: [
      { title: 'CIRA Survey Templates', type: 'Word Documents', available: false },
      { title: 'Stakeholder Guide', type: 'PDF Guide', available: false },
      { title: 'Benchmark Database', type: 'Online Tool', available: false }
    ]
  },
  tbl: {
    title: 'Triple Bottom Line Cultural Innovation',
    subtitle: 'TBL-CI Framework',
    description: 'An integrated framework for measuring the economic, social, and environmental returns from cultural innovation initiatives. TBL-CI ensures that cultural enterprises create holistic value across all three sustainability dimensions.',
    purpose: 'Cultural innovation should generate benefits beyond mere financial returns. TBL-CI provides a balanced scorecard approach that captures the full spectrum of value creation.',
    icon: '3B',
    color: 'from-sage to-ocean',
    components: [
      {
        title: 'Economic Returns Calculator',
        description: 'Measures direct and indirect financial benefits from cultural innovation activities.',
        metrics: ['Revenue and profit margins', 'Cost savings from cultural inputs', 'Investment returns', 'Economic multiplier effects']
      },
      {
        title: 'Social Impact Metrics',
        description: 'Quantifies improvements in community well-being and social cohesion.',
        metrics: ['Employment quality scores', 'Skill development outcomes', 'Community cohesion indices', 'Cultural identity strengthening']
      },
      {
        title: 'Environmental Index',
        description: 'Assesses environmental sustainability of cultural production processes.',
        metrics: ['Carbon footprint reduction', 'Resource efficiency gains', 'Biodiversity impacts', 'Waste reduction achievements']
      },
      {
        title: 'Integrated Reporting',
        description: 'Combines all three dimensions into a unified performance dashboard.',
        metrics: ['TBL composite score', 'Dimension balance ratio', 'Year-over-year trends', 'Stakeholder satisfaction']
      }
    ],
    howToUse: [
      { step: 1, title: 'Metrics Selection', description: 'Choose relevant metrics from each dimension based on your context.' },
      { step: 2, title: 'Baseline Measurement', description: 'Establish current performance levels across selected metrics.' },
      { step: 3, title: 'Target Setting', description: 'Set improvement targets for each dimension that balance competing priorities.' },
      { step: 4, title: 'Integrated Reporting', description: 'Create quarterly TBL reports that communicate holistic performance.' }
    ],
    relatedResources: [
      { title: 'TBL-CI Dashboard Template', type: 'Excel Template', available: false },
      { title: 'Metrics Definition Guide', type: 'PDF Guide', available: false },
      { title: 'Impact Measurement Toolkit', type: 'Complete Package', available: false }
    ]
  },
  ciss: {
    title: 'Cultural Innovation Sustainability Scorecard',
    subtitle: 'CISS Framework',
    description: 'A strategic evaluation tool that assesses the long-term viability of cultural innovation initiatives across four sustainability dimensions: economic, cultural, social, and environmental.',
    purpose: 'Many cultural innovation projects fail to achieve lasting impact. CISS helps identify sustainability risks early and guides interventions to ensure initiatives can thrive across generations.',
    icon: 'SS',
    color: 'from-lavender to-ocean',
    components: [
      {
        title: 'Economic Sustainability',
        description: 'Evaluates the financial self-sufficiency and market viability of initiatives.',
        metrics: ['Revenue diversification index', 'Dependency ratio (grants vs. earned)', 'Cash reserve months', 'Growth trajectory stability']
      },
      {
        title: 'Cultural Sustainability',
        description: 'Assesses the preservation and transmission of cultural knowledge and practices.',
        metrics: ['Knowledge transfer effectiveness', 'Youth engagement levels', 'Documentation completeness', 'Cultural protocol maintenance']
      },
      {
        title: 'Social Sustainability',
        description: 'Measures the ongoing community support and social license for operations.',
        metrics: ['Community approval ratings', 'Stakeholder engagement depth', 'Conflict resolution effectiveness', 'Leadership succession readiness']
      },
      {
        title: 'Environmental Sustainability',
        description: 'Evaluates environmental stewardship and resource management practices.',
        metrics: ['Resource depletion risk', 'Regenerative practice adoption', 'Climate adaptation readiness', 'Ecological footprint trends']
      }
    ],
    howToUse: [
      { step: 1, title: 'Annual Assessment', description: 'Conduct comprehensive CISS evaluations annually at minimum.' },
      { step: 2, title: 'Risk Identification', description: 'Highlight dimensions scoring below sustainability thresholds.' },
      { step: 3, title: 'Mitigation Planning', description: 'Develop risk mitigation strategies for vulnerable areas.' },
      { step: 4, title: 'Board Reporting', description: 'Present CISS results to governance bodies for strategic decisions.' }
    ],
    relatedResources: [
      { title: 'CISS Assessment Template', type: 'Excel Template', available: false },
      { title: 'Risk Mitigation Playbook', type: 'PDF Guide', available: false },
      { title: 'Board Presentation Template', type: 'PowerPoint', available: false }
    ]
  },
  pricing: {
    title: 'Cultural Product Pricing Framework',
    subtitle: 'Step-by-Step Pricing Tool',
    description: 'A comprehensive methodology for pricing cultural products and services that balances market competitiveness with fair compensation for cultural value and community benefit.',
    purpose: 'Cultural products often face pricing challenges - underpricing leads to exploitation, while overpricing limits market access. This framework guides principled pricing decisions.',
    icon: '$',
    color: 'from-gold to-sage',
    components: [
      {
        title: 'Cost Analysis',
        description: 'Comprehensive mapping of all costs involved in cultural production.',
        metrics: ['Direct material costs', 'Labor costs (fair wage basis)', 'Overhead allocation', 'Cultural IP licensing']
      },
      {
        title: 'Value Proposition',
        description: 'Articulating the unique value that cultural authenticity provides.',
        metrics: ['Authenticity premium potential', 'Story/narrative value', 'Scarcity and uniqueness factors', 'Social impact value']
      },
      {
        title: 'Market Positioning',
        description: 'Strategic placement within target market segments.',
        metrics: ['Competitor price mapping', 'Target segment willingness-to-pay', 'Channel margin requirements', 'Geographic price variations']
      },
      {
        title: 'Price Optimization',
        description: 'Finding the optimal price point that maximizes value capture.',
        metrics: ['Price elasticity testing', 'Bundle pricing strategies', 'Seasonal adjustment factors', 'Volume discount structures']
      }
    ],
    howToUse: [
      { step: 1, title: 'Cost Mapping', description: 'Document all costs including often-overlooked cultural labor and knowledge inputs.' },
      { step: 2, title: 'Value Articulation', description: 'Develop compelling narratives around cultural authenticity and impact.' },
      { step: 3, title: 'Market Research', description: 'Analyze competitor pricing and customer willingness-to-pay.' },
      { step: 4, title: 'Price Testing', description: 'Test price points with target customers before full market launch.' }
    ],
    relatedResources: [
      { title: 'Cost Calculator Spreadsheet', type: 'Excel Template', available: false },
      { title: 'Pricing Strategy Guide', type: 'PDF Guide', available: false },
      { title: 'Market Research Templates', type: 'Word Documents', available: false }
    ]
  }
}

import type { LucideIcon } from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  CM: BarChart3,
  RA: Target,
  '3B': TrendingUp,
  SS: Shield,
  $: FileText
}

interface PageProps {
  params: Promise<{ id: string }>
}

export default function FrameworkDetailPage({ params }: PageProps) {
  const { id } = use(params)

  const framework = frameworkData[id]

  if (!framework) {
    notFound()
  }

  const IconComponent = iconMap[framework.icon] || FileText

  return (
    <>
      {/* Hero Section */}
      <section className={`pt-32 pb-16 md:pt-48 md:pb-24 px-6 md:px-16 bg-gradient-to-br ${framework.color}`}>
        <div className="max-w-[1600px] mx-auto">
          <Link
            href="/tools"
            className="inline-flex items-center gap-2 text-ink/70 hover:text-ink transition-colors mb-8"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Tools
          </Link>

          <div className="flex items-start gap-6 mb-8">
            <div className="w-20 h-20 rounded-2xl bg-white/90 flex items-center justify-center shadow-lg">
              <span className="font-serif text-2xl text-ink">{framework.icon}</span>
            </div>
            <div>
              <p className="text-sm uppercase tracking-[0.15em] text-ink/60 mb-2">
                {framework.subtitle}
              </p>
              <h1 className="font-serif text-3xl md:text-5xl font-light leading-tight">
                {framework.title}
              </h1>
            </div>
          </div>

          <p className="text-lg md:text-xl leading-relaxed font-light max-w-3xl">
            {framework.description}
          </p>
        </div>
      </section>

      {/* Purpose Section */}
      <section className="py-16 md:py-24 px-6 md:px-16 bg-pearl">
        <div className="max-w-[1600px] mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <p className="section-label">Purpose</p>
              <h2 className="font-serif text-3xl md:text-4xl font-light mb-6">
                Why Use This Framework?
              </h2>
              <p className="text-lg text-stone leading-relaxed mb-8">
                {framework.purpose}
              </p>
              <Link
                href="/tools"
                className="btn-primary inline-flex items-center gap-2"
              >
                Take the Full Assessment
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
            <div className="bg-sand p-8 rounded-lg">
              <div className="flex items-center gap-4 mb-6">
                <IconComponent className="w-12 h-12 text-gold" strokeWidth={1.5} />
                <div>
                  <p className="font-medium text-lg">Framework Validation</p>
                  <p className="text-sm text-stone">Based on 362 case studies</p>
                </div>
              </div>
              <div className="space-y-3">
                <div className="flex justify-between items-center py-2 border-b border-ink/10">
                  <span className="text-stone">Components</span>
                  <span className="font-medium">{framework.components.length} dimensions</span>
                </div>
                <div className="flex justify-between items-center py-2 border-b border-ink/10">
                  <span className="text-stone">Implementation Steps</span>
                  <span className="font-medium">{framework.howToUse.length} steps</span>
                </div>
                <div className="flex justify-between items-center py-2">
                  <span className="text-stone">Resources Available</span>
                  <span className="font-medium">{framework.relatedResources.length} items</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Components Section */}
      <section className="py-16 md:py-24 px-6 md:px-16 bg-sand">
        <div className="max-w-[1600px] mx-auto">
          <p className="section-label">Framework Components</p>
          <h2 className="font-serif text-3xl md:text-4xl font-light mb-4">
            Key Dimensions
          </h2>
          <p className="text-stone text-lg max-w-3xl mb-12">
            The {framework.subtitle} evaluates initiatives across {framework.components.length} interconnected dimensions.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {framework.components.map((component, index) => (
              <div
                key={component.title}
                className="bg-pearl p-8 rounded-lg card-hover gold-border-top"
              >
                <div className="flex items-start gap-4 mb-4">
                  <span className="font-serif text-3xl text-gold/40">{String(index + 1).padStart(2, '0')}</span>
                  <div>
                    <h3 className="font-serif text-xl mb-2">{component.title}</h3>
                    <p className="text-stone">{component.description}</p>
                  </div>
                </div>
                {component.metrics && (
                  <div className="mt-6 pt-4 border-t border-ink/10">
                    <p className="text-xs uppercase tracking-[0.15em] text-stone mb-3">Key Metrics</p>
                    <ul className="space-y-2">
                      {component.metrics.map((metric) => (
                        <li key={metric} className="flex items-center gap-2 text-sm">
                          <span className="w-1.5 h-1.5 rounded-full bg-gold" />
                          {metric}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How to Use Section */}
      <section className="py-16 md:py-24 px-6 md:px-16 bg-pearl">
        <div className="max-w-[1600px] mx-auto">
          <p className="section-label">Implementation</p>
          <h2 className="font-serif text-3xl md:text-4xl font-light mb-4">
            How to Use This Framework
          </h2>
          <p className="text-stone text-lg max-w-3xl mb-12">
            Follow these steps to effectively apply the {framework.subtitle} to your initiatives.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {framework.howToUse.map((step) => (
              <div
                key={step.step}
                className="relative bg-sand p-6 rounded-lg"
              >
                <span className="absolute -top-3 -left-3 w-10 h-10 bg-gold text-ink rounded-full flex items-center justify-center font-serif text-lg">
                  {step.step}
                </span>
                <h3 className="font-medium mt-4 mb-2">{step.title}</h3>
                <p className="text-sm text-stone">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Resources Section */}
      <section className="py-16 md:py-24 px-6 md:px-16 bg-sand">
        <div className="max-w-[1600px] mx-auto">
          <p className="section-label">Resources</p>
          <h2 className="font-serif text-3xl md:text-4xl font-light mb-4">
            Downloads & Templates
          </h2>
          <p className="text-stone text-lg max-w-3xl mb-12">
            Supporting materials to help you implement the {framework.subtitle}.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {framework.relatedResources.map((resource) => (
              <div
                key={resource.title}
                className={`bg-pearl p-6 rounded-lg border ${resource.available ? 'border-gold' : 'border-ink/10'}`}
              >
                <div className="flex items-start justify-between mb-4">
                  <Download className={`w-8 h-8 ${resource.available ? 'text-gold' : 'text-stone/40'}`} strokeWidth={1.5} />
                  {resource.available ? (
                    <span className="text-xs bg-gold/20 text-gold px-2 py-1 rounded-full">Available</span>
                  ) : (
                    <span className="text-xs bg-ink/10 text-stone px-2 py-1 rounded-full">Coming Soon</span>
                  )}
                </div>
                <h3 className="font-medium mb-1">{resource.title}</h3>
                <p className="text-sm text-stone">{resource.type}</p>
                {resource.available && (
                  <button className="mt-4 text-sm text-gold font-medium hover:underline">
                    Download
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 md:py-24 px-6 md:px-16 bg-gradient-to-br from-ocean to-sage text-pearl text-center">
        <div className="max-w-3xl mx-auto">
          <h2 className="font-serif text-3xl md:text-4xl font-light mb-6">
            Ready to assess your initiative?
          </h2>
          <p className="text-lg opacity-90 mb-8">
            Use our comprehensive CIL Assessment Tool to evaluate your cultural innovation
            initiative across all 13 components and receive personalized recommendations.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/tools"
              className="bg-pearl text-ink px-8 py-4 rounded-full font-medium hover:-translate-y-1 transition-transform duration-300"
            >
              Take the Assessment
            </Link>
            <Link
              href="/framework"
              className="bg-transparent border border-pearl text-pearl px-8 py-4 rounded-full font-medium hover:bg-pearl/10 transition-colors duration-300"
            >
              Learn About CIRF
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
